### PR TITLE
Readme changes, changelog added, include package version in manual.

### PR DESCRIPTION
**Pull request by shaggytwodope**
The release version for example: 2.8 is not a version for a release.
This creates what I consider an issue with users possibly reporting
flaws or errors in the guides provided. Instead we mention version
from the packaging +Series: 2.8 as a solution.

I added a changelog as with all other projects. I think this is self
explainatory.

Some tweaks to the readme.

### CODE REVIEW

**Comment by linuxlite** [comment]
Thanks shaggy.

**Comment by shaggytwodope** [comment]
I'm not entirely sure Date published is as important, versioning is how we control all other software.
I'd like to suggest we re-word is a bit more.

CC @linuxlite @AdrianKoshka

**Comment by linuxlite** [comment]
I would suggest we ask the community whether or not they prefer the date. Since it is the people that use this resource, their feedback would prove insightful. Discussion can continue here for folks to give feedback - https://www.linuxliteos.com/forums/on-topic/new-linux-lite-help-manual-beta/

**Comment by shaggytwodope** [comment]
It's fine to poll community, But after thinking about this further.. since its published on the website as well I think it does belong there, just updated accordingly as it has been.

**Comment by AdrianKoshka** [comment]
Rewording the guide wouldn't be hard, though are you talking about the guide in general, or specific sections?

@shaggytwodope

**Comment by shaggytwodope** [comment]
@AdrianKoshka In regards to the date published part. Next to the version, but after thinking about it more I feel it belongs there.

**Comment by AdrianKoshka** [comment]
Okay.

**Pull request merged**
